apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-deployment
  namespace: mon-namespace
  labels:
    foo: deployment-label
  annotations:
    bar: deployment-annotation
spec:
  replicas: 3
  selector:
    matchLabels:
      baz: pod-label
  template:
    metadata:
      labels:
        baz: pod-label
      annotations:
        bing: pod-annotation
    spec:
      containers:
      - name: nginx
        image: cgr.dev/chainguard/nginx:latest
        ports:
          - containerPort: 8080
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        resources:
          limits:
            memory: "50Mi"
          requests:
            memory: "25Mi"
            cpu: "250m"
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true