apiVersion: v1
kind: Service
metadata:
  name: mon-service-loadbalancer
  namespace: mon-namespace
  labels:
    foo: service-label
  annotations:
    bar: service-annotation
spec:
  type: LoadBalancer
  selector:
    baz: pod-label
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80