apiVersion: v1
kind: Service
metadata:
  name: mon-service-nodeport
  namespace: mon-namespace
  labels:
    foo: service-label
  annotations:
    bar: service-annotation
spec:
  type: NodePort
  selector:
    baz: pod-label
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8082
