all:
  hosts:
    localhost:
      ansible_connection: local
  children:
    backend:
      hosts:
        server1:
          ansible_host: 127.0.0.1
          ansible_port: 80
    db:
      hosts:
        db1:
          ansible_host: 127.0.0.1
          ansible_port: 5432
          ansible_user: db_user
